baseURL = ''
languageCode = 'en-us'
title = "Spar"
theme = "spar"
relativeURLS = true

[menu]

[[menu.main]]
    name    = "About"
    identifier = "menu.about"
    url = "about/"

[[menu.main]]
    name    = "Merch"
    identifier = "menu.merch"
    url = "https://www.redbubble.com/"

