baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Spar"
theme = "spar"


[menu]

[[menu.main]]
    name    = "About"    
    pageRef = "/about.md"

[[menu.main]]
    name    = "Merch"    
    pageRef = "https://www.redbubble.com/"

